use_frameworks!
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'project' do

#pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RxSwift'
pod 'Moya/RxSwift'
pod 'SnapKit'
pod 'SwiftTheme'
pod 'Reusable'
pod 'RxDataSources'
pod 'Toast-Swift', '~> 5.0.0'
pod 'Kingfisher'
end
