use_frameworks!
platform :ios, '8.0'
target 'project' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Moya'
pod 'SnapKit'
pod 'RxSwift'
pod 'SDWebImage'
pod 'SwiftTheme'
pod 'Reusable'
pod 'RxDataSources', '~> 4.0'
end
