use_frameworks!
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'project' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Moya'
pod 'SnapKit'
pod 'RxSwift'
pod 'SDWebImage'
pod 'SwiftTheme'
pod 'Reusable'
pod 'RxDataSources', '~> 4.0'
pod 'Toast-Swift', '~> 5.0.0'
pod 'Kingfisher'
end
