use_frameworks!
platform :ios, '9.0'
target 'hybirdDemo' do
	pod 'AppCenter'
  pod 'FBLazyVector', :path => "./RNComponent/node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "./RNComponent/node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "./RNComponent/node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "./RNComponent/node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => './RNComponent/node_modules/react-native/'
  pod 'React-Core', :path => './RNComponent/node_modules/react-native/'
  pod 'React-CoreModules', :path => './RNComponent/node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => './RNComponent/node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => './RNComponent/node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => './RNComponent/node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => './RNComponent/node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => './RNComponent/node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => './RNComponent/node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => './RNComponent/node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => './RNComponent/node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => './RNComponent/node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => './RNComponent/node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => './RNComponent/node_modules/react-native/'

  pod 'React-cxxreact', :path => './RNComponent/node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => './RNComponent/node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => './RNComponent/node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => './RNComponent/node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "./RNComponent/node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "./RNComponent/node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => './RNComponent/node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => './RNComponent/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => './RNComponent/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => './RNComponent/node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => './RNComponent/node_modules/react-native-gesture-handler'
  
end
